colors = ['firebrick',
          'orangered',
          'sandybrown',
          'gold',
          'yellowgreen',
          'lightgreen',
          'mediumspringgreen',
          'turquoise',
          'darkturquoise',
          'deepskyblue',
          'mediumslateblue',
          'blueviolet',
          'violet',
          'hotpink'
          ]